from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class SafetyCompanionTests(unittest.TestCase):
    def test_agent_has_safety_support_personality(self):
        source = (ROOT / "livekit_agent.py").read_text()
        self.assertIn("soft-spoken emotional companion named Luulu", source)
        self.assertIn("open questions", source)
        self.assertIn("acknowledge effort", source)
        self.assertIn("reflect feelings", source)
        self.assertIn("summar", source)
        self.assertIn("988", source)
        self.assertIn("emergency services", source)
        self.assertIn("Ask one question at a time", source)
        self.assertIn("five stages of grief", source)
        self.assertIn("denial", source)
        self.assertIn("anger", source)
        self.assertIn("bargaining", source)
        self.assertIn("depression", source)
        self.assertIn("acceptance", source)
        self.assertIn("session.generate_reply", source)
        self.assertIn("Hi, I'm Luulu", source)
        self.assertIn("Always introduce yourself as Luulu", source)
        self.assertIn("professional mental-health support", source)
        self.assertIn("Avoid figurative language", source)
        self.assertIn("What's happening right now?", source)
        self.assertIn("trained support companion", source)

    def test_agent_integrates_livekit_inference_and_moss(self):
        source = (ROOT / "livekit_agent.py").read_text()
        self.assertIn("inference.STT", source)
        self.assertIn("inference.LLM", source)
        self.assertIn("inference.TTS", source)
        self.assertIn("elevenlabs.TTS", source)
        self.assertIn("ELEVEN_API_KEY", source)
        self.assertIn("ELEVENLABS_VOICE_ID", source)
        self.assertIn('agent_name=AGENT_NAME', source)
        self.assertIn("MossClient", source)
        self.assertIn("on_user_turn_completed", source)

    def test_moss_index_contains_safety_knowledge(self):
        source = (ROOT / "moss_build_index.py").read_text()
        self.assertIn("safety-companion", source)
        self.assertIn("supportive-check-in", source)
        self.assertIn("crisis-escalation", source)
        self.assertIn("grounding-regulation", source)
        self.assertIn("social-reconnection", source)
        self.assertIn("behavior-experiments", source)

    def test_web_server_has_crisis_guardrails(self):
        source = (ROOT / "server.mjs").read_text()
        page = (ROOT / "public" / "index.html").read_text()
        app = (ROOT / "public" / "app.js").read_text()
        styles = (ROOT / "public" / "styles.css").read_text()
        self.assertIn("warm emotional companion", source)
        self.assertIn("You are Luulu", source)
        self.assertIn("detectsCrisis", source)
        self.assertIn("call/text 988", source)
        self.assertIn("emergency services", source)
        self.assertIn("gentle listening", source)
        self.assertIn("/api/metrics", source)
        self.assertIn("/api/metrics/active", source)
        self.assertIn("/api/metrics/page-view", source)
        self.assertIn("/api/livekit-webhook", source)
        self.assertIn("/api/metrics/contact", source)
        self.assertIn("WebhookReceiver", source)
        self.assertIn("Luulu is there for you", page)
        self.assertIn("Call when you need someone", page)
        self.assertIn("Say the messy version", page)
        self.assertIn("name what feels heavy", page)
        self.assertIn("one small next step", page)
        self.assertIn("Start with anything", page)
        self.assertIn("Tell Luulu anything", page)
        self.assertIn("Practice social skills with Luulu", page)
        self.assertIn("No shame", page)
        self.assertIn("Here 24/7", page)
        self.assertIn("24/7 available", page)
        self.assertIn("better choices", page)
        self.assertIn("no waiting", page)
        self.assertNotIn("emotion-scroll", page)
        self.assertIn("Private AI companion", page)
        self.assertIn("More Luulu is coming", page)
        self.assertIn("events coming up and fun things", page)
        self.assertIn("First name", page)
        self.assertIn("Last name", page)
        self.assertIn("Phone number for Luulu updates", page)
        self.assertIn("Email", page)
        self.assertIn("Subscribe me to Luulu's mailing list and phone updates", page)
        self.assertIn("Subscribe", page)
        self.assertIn("+1 (415) 908-5000", page)
        self.assertIn("No recordings", page)
        self.assertIn("No recordings", page)
        self.assertIn("visitors", page)
        self.assertIn("online now", page)
        self.assertIn("call taps", page)
        self.assertIn("calls", page)
        self.assertIn("Save Luulu to contacts", page)
        self.assertIn("/luulu.vcf", page)
        self.assertNotIn("download=\"Luulu.vcf\"", page)
        self.assertIn("/lulu-contact.jpg", page)
        self.assertTrue((ROOT / "public" / "lulu-contact.jpg").exists())
        self.assertIn("data-track-call", page)
        self.assertIn("data-track-contact", page)
        self.assertIn("sendBeacon", app)
        self.assertIn("handleLeadSubmit", app)
        self.assertIn("/api/leads", app)
        self.assertIn("postActiveMetric", app)
        self.assertIn("postPageViewMetric", app)
        self.assertIn("pageVisitors", app)
        self.assertIn("callClicks", app)
        self.assertIn("sessionRooms", app)
        self.assertIn("activeNow", app)
        self.assertNotIn("hue-rotate", styles)
        self.assertIn("/api/leads", source)
        self.assertIn("LIVEKIT_UNIQUE_PARTICIPANTS_BASE", source)
        self.assertIn("uniqueParticipants", source)
        self.assertIn("sessionRooms", source)
        self.assertIn("saveLeadToNotion", source)
        self.assertIn("findDuplicateLead", source)
        self.assertIn("duplicate_lead", source)
        self.assertIn("matchedBy", source)
        self.assertIn("/v1/databases/", source)
        self.assertIn("NOTION_API_KEY", source)
        self.assertIn("NOTION_LEADS_DATABASE_ID", source)
        self.assertIn("createLuuluVcard", source)
        self.assertIn("ORG:Friend & Companion", source)
        self.assertIn("TITLE:AI Emotional Companion", source)
        self.assertIn("PHOTO;ENCODING=b;TYPE=JPEG", source)
        self.assertIn("text/x-vcard", source)
        self.assertIn("inline; filename", source)
        self.assertIn("/luulu.vcf", (ROOT / "vercel.json").read_text())
        self.assertTrue((ROOT / "public" / "robots.txt").exists())
        self.assertTrue((ROOT / "public" / "sitemap.xml").exists())
        self.assertIn("https://withluulu.com/", page)
        self.assertIn('rel="canonical"', page)
        self.assertIn("application/ld+json", page)
        self.assertIn("SoftwareApplication", page)


if __name__ == "__main__":
    unittest.main()
